name: 'Build Image'
description: 'Build Image and push to Digital Ocean Repository'
inputs:
  accessToken:
    description: 'Digital Ocean API Access Token'
    required: true
  repository:
    description: 'Digital Ocean Repository'
    required: true    
  tag:
    description: 'Tag to use'
    tag: ${{ steps.short-sha.outputs.sha }}
runs:
  using: "composite"
  steps:
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        
      - name: Build container image
        run: docker build -t registry.digitalocean.com/${{ inputs.repository }}:${{ inputs.tag }} .
        shell: bash

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ inputs.accessToken }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200
        shell: bash

      - name: Push image to DigitalOcean Container Registry
        run: docker push registry.digitalocean.com/${{ inputs.repository }}:${{ inputs.tag }}
        shell: bash
